# Generated by Django 4.0.5 on 2022-07-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0004_mytext_categoty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytext',
            old_name='categoty',
            new_name='category',
        ),
    ]
