# Generated by Django 4.0.5 on 2022-07-08 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0005_rename_categoty_mytext_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytext',
            old_name='image_url',
            new_name='img_url',
        ),
    ]
