# Generated by Django 4.0.5 on 2022-07-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0006_rename_image_url_mytext_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytext',
            name='img_url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
