# Generated by Django 4.0.5 on 2022-08-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0009_mytext_lecture_title1_mytext_lecture_title2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video4',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
